# Generated by Django 5.1.1 on 2024-10-13 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0003_attendance_gallery'),
    ]

    operations = [
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Target_muscle', models.CharField(max_length=25)),
                ('Exercise_1', models.CharField(max_length=25)),
                ('Exercise_2', models.CharField(max_length=25)),
                ('Exercise_3', models.CharField(max_length=25)),
                ('Exercise_4', models.CharField(max_length=25)),
            ],
        ),
    ]
