# Generated by Django 5.1.1 on 2024-12-12 05:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0005_chatbot'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('response', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='chatbot',
        ),
        migrations.RenameField(
            model_name='attendance',
            old_name='Login',
            new_name='login',
        ),
        migrations.RenameField(
            model_name='attendance',
            old_name='Logout',
            new_name='logout',
        ),
        migrations.RenameField(
            model_name='attendance',
            old_name='phonenumber',
            new_name='phone_number',
        ),
        migrations.RenameField(
            model_name='attendance',
            old_name='Selectdate',
            new_name='select_date',
        ),
        migrations.RenameField(
            model_name='attendance',
            old_name='SelectWorkout',
            new_name='trained_by',
        ),
        migrations.RenameField(
            model_name='attendance',
            old_name='TrainedBy',
            new_name='workout',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='phonenumber',
            new_name='phone_number',
        ),
        migrations.RenameField(
            model_name='enrollment',
            old_name='Address',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='enrollment',
            old_name='DOB',
            new_name='dob',
        ),
        migrations.RenameField(
            model_name='enrollment',
            old_name='DueDate',
            new_name='due_date',
        ),
        migrations.RenameField(
            model_name='enrollment',
            old_name='Email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='enrollment',
            old_name='FullName',
            new_name='full_name',
        ),
        migrations.RenameField(
            model_name='enrollment',
            old_name='Gender',
            new_name='gender',
        ),
        migrations.RenameField(
            model_name='enrollment',
            old_name='SelectMembershipplan',
            new_name='membership_plan',
        ),
        migrations.RenameField(
            model_name='enrollment',
            old_name='paymentStatus',
            new_name='payment_status',
        ),
        migrations.RenameField(
            model_name='enrollment',
            old_name='PhoneNumber',
            new_name='phone_number',
        ),
        migrations.RenameField(
            model_name='enrollment',
            old_name='Reference',
            new_name='reference',
        ),
        migrations.RenameField(
            model_name='enrollment',
            old_name='timeStamp',
            new_name='timestamp',
        ),
        migrations.RenameField(
            model_name='enrollment',
            old_name='SelectTrainer',
            new_name='trainer',
        ),
        migrations.RenameField(
            model_name='gallery',
            old_name='timeStamp',
            new_name='timestamp',
        ),
        migrations.RenameField(
            model_name='trainer',
            old_name='timeStamp',
            new_name='timestamp',
        ),
        migrations.RenameField(
            model_name='workout',
            old_name='Exercise_1',
            new_name='exercise_1',
        ),
        migrations.RenameField(
            model_name='workout',
            old_name='Exercise_2',
            new_name='exercise_2',
        ),
        migrations.RenameField(
            model_name='workout',
            old_name='Exercise_3',
            new_name='exercise_3',
        ),
        migrations.RenameField(
            model_name='workout',
            old_name='Exercise_4',
            new_name='exercise_4',
        ),
        migrations.RenameField(
            model_name='workout',
            old_name='Target_muscle',
            new_name='target_muscle',
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='Price',
        ),
        migrations.AlterField(
            model_name='membershipplan',
            name='price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='salary',
            field=models.IntegerField(),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
